### ISSUE TITLE
Please sign artifacts

### ISSUE THREAD

**Issue by technomancy** [clj-commons/useful#28]
It would be great if you could deploy a signature for the latest
release of this library and make it a habit of deploying signed jars
in the future.

Here's a quick description of how to sign already-deployed jars on Clojars:

https://github.com/technomancy/leiningen/wiki/SigningDeployedJars

**Comment by danielcompton** [comment]
I've released 0.11.6 which is signed by my Keybase keys at https://keybase.io/danielcompton. I _think_ I did this correctly...
